<?php

/**
 * BaseSeasons
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $name
 * @property varchar $event
 * @property timestamp $start
 * @property timestamp $end
 * @property varchar $link
 * @property varchar $logo
 * @property boolean $active
 * @property Doctrine_Collection $Matchs
 * @property Doctrine_Collection $Advertising
 * @property Doctrine_Collection $TeamsInSeasons
 * 
 * @method integer             get()               Returns the current record's "id" value
 * @method varchar             get()               Returns the current record's "name" value
 * @method varchar             get()               Returns the current record's "event" value
 * @method timestamp           get()               Returns the current record's "start" value
 * @method timestamp           get()               Returns the current record's "end" value
 * @method varchar             get()               Returns the current record's "link" value
 * @method varchar             get()               Returns the current record's "logo" value
 * @method boolean             get()               Returns the current record's "active" value
 * @method Doctrine_Collection get()               Returns the current record's "Matchs" collection
 * @method Doctrine_Collection get()               Returns the current record's "Advertising" collection
 * @method Doctrine_Collection get()               Returns the current record's "TeamsInSeasons" collection
 * @method Seasons             set()               Sets the current record's "id" value
 * @method Seasons             set()               Sets the current record's "name" value
 * @method Seasons             set()               Sets the current record's "event" value
 * @method Seasons             set()               Sets the current record's "start" value
 * @method Seasons             set()               Sets the current record's "end" value
 * @method Seasons             set()               Sets the current record's "link" value
 * @method Seasons             set()               Sets the current record's "logo" value
 * @method Seasons             set()               Sets the current record's "active" value
 * @method Seasons             set()               Sets the current record's "Matchs" collection
 * @method Seasons             set()               Sets the current record's "Advertising" collection
 * @method Seasons             set()               Sets the current record's "TeamsInSeasons" collection
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSeasons extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seasons');
        $this->hasColumn('id', 'integer', 20, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 20,
             ));
        $this->hasColumn('name', 'varchar', 50, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('event', 'varchar', 50, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('start', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('end', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('link', 'varchar', 100, array(
             'type' => 'varchar',
             'length' => 100,
             ));
        $this->hasColumn('logo', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Matchs', array(
             'local' => 'id',
             'foreign' => 'season_id'));

        $this->hasMany('Advertising', array(
             'local' => 'id',
             'foreign' => 'season_id'));

        $this->hasMany('TeamsInSeasons', array(
             'local' => 'id',
             'foreign' => 'season_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}