<?php

/**
 * BasePlayers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $match_id
 * @property integer $map_id
 * @property varchar $player_key
 * @property enum $team
 * @property varchar $ip
 * @property varchar $steamid
 * @property enum $first_side
 * @property enum $current_side
 * @property varchar $pseudo
 * @property integer $nb_kill
 * @property integer $assist
 * @property integer $death
 * @property integer $point
 * @property integer $hs
 * @property integer $defuse
 * @property integer $bombe
 * @property integer $tk
 * @property integer $nb1
 * @property integer $nb2
 * @property integer $nb3
 * @property integer $nb4
 * @property integer $nb5
 * @property integer $nb1kill
 * @property integer $nb2kill
 * @property integer $nb3kill
 * @property integer $nb4kill
 * @property integer $nb5kill
 * @property integer $pluskill
 * @property integer $firstkill
 * @property Matchs $Match
 * @property Maps $Map
 * @property Doctrine_Collection $PlayersSnapshot
 * @property Doctrine_Collection $RoundSummary
 * @property Doctrine_Collection $PlayerKill
 * @property Doctrine_Collection $PlayersHeatmap
 * 
 * @method integer             get()                Returns the current record's "id" value
 * @method integer             get()                Returns the current record's "match_id" value
 * @method integer             get()                Returns the current record's "map_id" value
 * @method varchar             get()                Returns the current record's "player_key" value
 * @method enum                get()                Returns the current record's "team" value
 * @method varchar             get()                Returns the current record's "ip" value
 * @method varchar             get()                Returns the current record's "steamid" value
 * @method enum                get()                Returns the current record's "first_side" value
 * @method enum                get()                Returns the current record's "current_side" value
 * @method varchar             get()                Returns the current record's "pseudo" value
 * @method integer             get()                Returns the current record's "nb_kill" value
 * @method integer             get()                Returns the current record's "assist" value
 * @method integer             get()                Returns the current record's "death" value
 * @method integer             get()                Returns the current record's "point" value
 * @method integer             get()                Returns the current record's "hs" value
 * @method integer             get()                Returns the current record's "defuse" value
 * @method integer             get()                Returns the current record's "bombe" value
 * @method integer             get()                Returns the current record's "tk" value
 * @method integer             get()                Returns the current record's "nb1" value
 * @method integer             get()                Returns the current record's "nb2" value
 * @method integer             get()                Returns the current record's "nb3" value
 * @method integer             get()                Returns the current record's "nb4" value
 * @method integer             get()                Returns the current record's "nb5" value
 * @method integer             get()                Returns the current record's "nb1kill" value
 * @method integer             get()                Returns the current record's "nb2kill" value
 * @method integer             get()                Returns the current record's "nb3kill" value
 * @method integer             get()                Returns the current record's "nb4kill" value
 * @method integer             get()                Returns the current record's "nb5kill" value
 * @method integer             get()                Returns the current record's "pluskill" value
 * @method integer             get()                Returns the current record's "firstkill" value
 * @method Matchs              get()                Returns the current record's "Match" value
 * @method Maps                get()                Returns the current record's "Map" value
 * @method Doctrine_Collection get()                Returns the current record's "PlayersSnapshot" collection
 * @method Doctrine_Collection get()                Returns the current record's "RoundSummary" collection
 * @method Doctrine_Collection get()                Returns the current record's "PlayerKill" collection
 * @method Doctrine_Collection get()                Returns the current record's "PlayersHeatmap" collection
 * @method Players             set()                Sets the current record's "id" value
 * @method Players             set()                Sets the current record's "match_id" value
 * @method Players             set()                Sets the current record's "map_id" value
 * @method Players             set()                Sets the current record's "player_key" value
 * @method Players             set()                Sets the current record's "team" value
 * @method Players             set()                Sets the current record's "ip" value
 * @method Players             set()                Sets the current record's "steamid" value
 * @method Players             set()                Sets the current record's "first_side" value
 * @method Players             set()                Sets the current record's "current_side" value
 * @method Players             set()                Sets the current record's "pseudo" value
 * @method Players             set()                Sets the current record's "nb_kill" value
 * @method Players             set()                Sets the current record's "assist" value
 * @method Players             set()                Sets the current record's "death" value
 * @method Players             set()                Sets the current record's "point" value
 * @method Players             set()                Sets the current record's "hs" value
 * @method Players             set()                Sets the current record's "defuse" value
 * @method Players             set()                Sets the current record's "bombe" value
 * @method Players             set()                Sets the current record's "tk" value
 * @method Players             set()                Sets the current record's "nb1" value
 * @method Players             set()                Sets the current record's "nb2" value
 * @method Players             set()                Sets the current record's "nb3" value
 * @method Players             set()                Sets the current record's "nb4" value
 * @method Players             set()                Sets the current record's "nb5" value
 * @method Players             set()                Sets the current record's "nb1kill" value
 * @method Players             set()                Sets the current record's "nb2kill" value
 * @method Players             set()                Sets the current record's "nb3kill" value
 * @method Players             set()                Sets the current record's "nb4kill" value
 * @method Players             set()                Sets the current record's "nb5kill" value
 * @method Players             set()                Sets the current record's "pluskill" value
 * @method Players             set()                Sets the current record's "firstkill" value
 * @method Players             set()                Sets the current record's "Match" value
 * @method Players             set()                Sets the current record's "Map" value
 * @method Players             set()                Sets the current record's "PlayersSnapshot" collection
 * @method Players             set()                Sets the current record's "RoundSummary" collection
 * @method Players             set()                Sets the current record's "PlayerKill" collection
 * @method Players             set()                Sets the current record's "PlayersHeatmap" collection
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlayers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('players');
        $this->hasColumn('id', 'integer', 20, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 20,
             ));
        $this->hasColumn('match_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('map_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('player_key', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('team', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'a',
              1 => 'b',
              2 => 'other',
             ),
             'default' => 'other',
             ));
        $this->hasColumn('ip', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('steamid', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('first_side', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'ct',
              1 => 't',
              2 => 'other',
             ),
             ));
        $this->hasColumn('current_side', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'ct',
              1 => 't',
              2 => 'other',
             ),
             ));
        $this->hasColumn('pseudo', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('nb_kill', 'integer', 5, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 5,
             ));
        $this->hasColumn('assist', 'integer', 5, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 5,
             ));
        $this->hasColumn('death', 'integer', 5, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 5,
             ));
        $this->hasColumn('point', 'integer', 5, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 5,
             ));
        $this->hasColumn('hs', 'integer', 5, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 5,
             ));
        $this->hasColumn('defuse', 'integer', 5, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 5,
             ));
        $this->hasColumn('bombe', 'integer', 5, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 5,
             ));
        $this->hasColumn('tk', 'integer', 5, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 5,
             ));
        $this->hasColumn('nb1', 'integer', 5, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 5,
             ));
        $this->hasColumn('nb2', 'integer', 5, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 5,
             ));
        $this->hasColumn('nb3', 'integer', 5, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 5,
             ));
        $this->hasColumn('nb4', 'integer', 5, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 5,
             ));
        $this->hasColumn('nb5', 'integer', 5, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 5,
             ));
        $this->hasColumn('nb1kill', 'integer', 5, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 5,
             ));
        $this->hasColumn('nb2kill', 'integer', 5, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 5,
             ));
        $this->hasColumn('nb3kill', 'integer', 5, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 5,
             ));
        $this->hasColumn('nb4kill', 'integer', 5, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 5,
             ));
        $this->hasColumn('nb5kill', 'integer', 5, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 5,
             ));
        $this->hasColumn('pluskill', 'integer', 5, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 5,
             ));
        $this->hasColumn('firstkill', 'integer', 5, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Matchs as Match', array(
             'local' => 'match_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Maps as Map', array(
             'local' => 'map_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('PlayersSnapshot', array(
             'local' => 'id',
             'foreign' => 'player_id'));

        $this->hasMany('RoundSummary', array(
             'local' => 'id',
             'foreign' => 'best_killer'));

        $this->hasMany('PlayerKill', array(
             'local' => 'id',
             'foreign' => 'killer_id'));

        $this->hasMany('PlayersHeatmap', array(
             'local' => 'id',
             'foreign' => 'player_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}