<?php

/**
 * BaseTeamPlayers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $team_id
 * @property varchar $steamid64
 * @property varchar $name
 * @property Teams $Teams
 * 
 * @method integer     get()          Returns the current record's "id" value
 * @method integer     get()          Returns the current record's "team_id" value
 * @method varchar     get()          Returns the current record's "steamid64" value
 * @method varchar     get()          Returns the current record's "name" value
 * @method Teams       get()          Returns the current record's "Teams" value
 * @method TeamPlayers set()          Sets the current record's "id" value
 * @method TeamPlayers set()          Sets the current record's "team_id" value
 * @method TeamPlayers set()          Sets the current record's "steamid64" value
 * @method TeamPlayers set()          Sets the current record's "name" value
 * @method TeamPlayers set()          Sets the current record's "Teams" value
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTeamPlayers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('team_players');
        $this->hasColumn('id', 'integer', 20, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 20,
             ));
        $this->hasColumn('team_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('steamid64', 'varchar', 20, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('name', 'varchar', 50, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Teams', array(
             'local' => 'team_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}