<?php
// auto-generated by sfViewConfigHandler
// date: 2026/02/27 02:04:41
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'eBot :: Your ingame bot manager for CS:GO', false, false);

  $response->addStylesheet('bootstrap.min.css', '', array ());
  $response->addStylesheet('bootstrap-responsive.min.css', '', array ());
  $response->addStylesheet('tipsy.css', '', array ());
  $response->addStylesheet('datatable.bootstrap.css', '', array ());
  $response->addStylesheet('flags.css', '', array ());
  $response->addStylesheet('hubinfo.min.css', '', array ());
  $response->addJavascript('jquery-1.8.2.min.js', '', array ());
  $response->addJavascript('bootstrap.min.js', '', array ());
  $response->addJavascript('jquery.validate.min.js', '', array ());
  $response->addJavascript('jquery.tipsy.js', '', array ());
  $response->addJavascript('jquery.tablesorter.min.js', '', array ());
  $response->addJavascript('jquery.datatable.min.js', '', array ());
  $response->addJavascript('datatable.bootstrap.js', '', array ());
  $response->addJavascript('heatmap.js', '', array ());
  $response->addJavascript('raphael-min.js', '', array ());
  $response->addJavascript('jquery.iphone-switch.js', '', array ());
  $response->addJavascript('hubinfo.min.js', '', array ());


