# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: "mysql:host=mysqldb;dbname=ebotcs2"
      username: ebotcs2
      password: bbd79a5f7ce2e4de27ef612e032a5d93
