<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2026/02/27 02:04:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=mysqldb;dbname=ebotcs2',
  'username' => 'ebotcs2',
  'password' => 'bbd79a5f7ce2e4de27ef612e032a5d93',
  'name' => 'doctrine',
)),);
